
# Mongo Database Details
mongo:
  uri-mode: false
  mongo-uri: ''
  address: "127.0.0.1"
  port: 27017
  database: "dbname"
  authentication: false
  username: "username"
  password: "password"

# Redis Database Details
redis:
  address: "127.0.0.1"
  port: 6379
  password: "password"

# Network settings
network:
  # These colors should be ChatColors acceptable inputs: DARK_RED, RED, AQUA, GOLD, DARK_GREEN... etc
  main-color: "GOLD"
  middle-color: "YELLOW"
  secondary-color: "YELLOW"
  ip: "yourserver.com"
  website: "yourserver.com"
  store: "store.yourserver.com"
  discord: "discord.yourserver.com"
  teamspeak: "ts.yourserver.com"
  twitter: "twitter.com/yourserver"

server:
  # This should be the same name you put in your bungeecord config.yml
  name: "hub-1"
  displayname: "Hub 1"
  group: "Hubs"
  region: "EU"
  date-format: "dd/MM/yyyy hh:mm:ss a"
  # If a player with the rank Admin that has the child mod will inherit mod perms. If the mod rank has the child Trial-Mod
  # and the passthrough is on admin will get both trial and mod perms.
  passthrough-children: false
  # Should this servers player count and max player count towards the total?
  count-players: true
  console-name: "&4&lConsole"
  # Should the '*' permission be enabled?
  star-perm-enabled: true
  # Should the alts system be enabled?
  alts-enabled: true

security:
  enabled: true
  # If a user gets a rank in this list and they aren't security verified they'll be punished
  ranks-to-trigger: 
  - "Owner"
  - "Developer"
  # Should a user who gets opped be punished if they aren't security verified
  op-trigger: true
  # Should security users be automatically opped?
  auto-op: true
  # Should the user that opped or gave someone a rank be punished if the person they gave it to isn't security verified
  punish-sender: true

filter:
  enabled: true
  # Should links be part of the hard filter?
  links-hard: false
  # Send the filtered message to the sender only
  ghost-mode: false
  # Send the sender a message that their message got filtered
  alert-filter: true
  whitelisted-links: 
  - "yourserver.com"

# Whitelist Settings
whitelist:
  # If enabled the whitelist will be using names instead of uuid's.
  # Please clear your whitelist list before changing this option!
  # This will be same as UUID but instead of UUID it will be getting lowerCaseName
  name-based: false
  enabled: false
  access-rank: "Default"
  # DO NOT EDIT!
  access-types: 
  - "RANK"
  - "UUID"
  players: 
  - "uuid"
  - "uuid1"
