
staff:
  webhook-url: ''
  join:
    color: "#bd0010"
    title: "<player> joined the network"
    description: 
    - "<player> has joined <server> on <proxy>"
  switch:
    color: "#bd0010"
    title: "<player> switched servers"
    description: 
    - "<player> has joined <to> from <from>"
  leave:
    color: "#bd0010"
    title: "<player> left the network"
    description: 
    - "<player> has left from <server>"

server:
  webhook-url: ''
  startup:
    color: "#bd0010"
    title: "<server> has started"
    description: 
    - "<server> (<region>) has just started up"
  shutdown:
    color: "#bd0010"
    title: "<server> has stopped"
    description: 
    - "<server> (<region>) has just shut down"

grant:
  webhook-url: ''
  execute-grant:
    color: "#bd0010"
    title: "Grant Executed for <player>"
  revoke-grant:
    color: "#bd0010"
    title: "Grant Revoked for <player>"

punishment:
  webhook-url: ''
  execute-punishment:
    color: "#bd0010"
    title: "Punishment Executed for <player>"
  revoke-punishment:
    color: "#bd0010"
    title: "Punishment Revoked for <player>"
