# This is the configuration file for the PvP-Bots of Bolt. There's a lot of things to configure along
# with the knockback profiles specifically made for the bots. The default config contains four bot presets
# that have pre-defined combat settings which will be perfectly fine if you use them as is. As always if you
# need any help, feel free to contact customer support at https://dsc.gg/refine

BOT-SETTINGS:
  
  # Should the bots be enabled at all?
  ENABLED: true
  
  # If for some reason your hits turn into combo mode for bots, try this.
  FIX-COMBO-MODE-HITS: false
  
  # Should we reduce the bot's attack range when it's getting comboed for more smoother combos.
  REDUCE-RANGE-ON-COMBO: true
  
  # This will disable bolt's bot knockback system and use spigot's knockback system instead.
  # It is recommended to only enable this if you know the spigot will support Citizens NPC knockback.
  # If the spigot uses a kohi-based knockback system or mSpigot based knockback system, then it's likely it will.
  SPIGOT-BASED-KB: false
  
  # This is the movement speed for normal non-tryhard bots.
  NORMAL-MOVEMENT-SPEED: 1.0
  
  # This is the movement speed for tryhard bots.
  TRY-HARD-MOVEMENT-SPEED: 1.15
  
  # This is the movement speed for that is applied when bot has a speed potion effect.
  SPEED-EFFECT-MOVEMENT-SPEED: 1.29
  
  # This is the maximum amount of bot matches that can be running at once.
  MAXIMUM-BOT-MATCHES-AT-ONCE: 10
  
  # Bot modes are essentially pre-determined logic related to the kit for the bot.
  # For example, Speed PvP mode would be catering to Speed kits like NoDebuff, Debuff etc.
  # Meanwhile, UHC mode would be catering to BuildUHC or SG type of kits. (Keep in mind, Bot cannot build right now)
  MODES:
    # This is the default bot-mode, which has no logic pre-determined.
    # Kits like Sumo which do not have any logic except just knocking the player off the platform are applicable here.
    DEFAULT:
      KITS:
        - "Sumo"
    SPEED-PVP:
      # Do you want to enable the Speed PvP bot mode?
      ENABLED: true
      
      # Configure what kits do you want assigned to this bot mode.
      KITS:
        - "NoDebuff"
        - "Debuff"
    GOLDEN-APPLE:
      # Do you want to enable the Golden Apple bot mode?
      ENABLED: true
      
      # Configure what kits do you want assigned to this bot mode.
      KITS:
        - "Gapple"
        - "Combo"
    UHC:
      # Do you want to enable the UHC bot mode?
      ENABLED: true
      
      # Configure what kits do you want assigned to this bot mode.
      KITS:
        - "BuildUHC"
        - "FinalUHC"
        - "SG"
    SOUP:
      # Do you want to enable the Soup bot mode?
      ENABLED: true
      
      # Configure what kits do you want assigned to this bot mode.
      KITS:
        - "Soup"

# Bolt randomly picks a name from this list, although if you want to enforce only one name
# then just put one single name here. Note that putting any color codes here won't work, that's in the Bot-Prefix
BOT-NAMES:
  - "Marcel"
  - "Jewdah"
  - "Defused"
  - "OhEmilyyy"
  - "Amaan"
  - "Zefew"
  - "Miami"
  - "ByRez"
  - "Tryhard"
  - "PotFast"
  - "LigmaSpark"
  - "Brewage"
  - "Bl4stymineman"
  - "sbeenz"
  - "Clare"
  - "kayalust"
  - "ZIBLACKINGGG"
  - "Staind"
  - "Dowze"
  - "SumTing"
  - "gopu"
  - "Scholar"
  - "idiol"
  - "CL0CK"
  - "flaxeneel2"
  - "Zeynah"
  - "Adviser"
  - "Dreamer_420"
  - "Rases"
  - "AYEAR"
  - "Labdy"
  - "Mnyue"
  - "VolcrzR"
  - "Dubai"
  - "Eloies"
  - "Vers"
  - "Hydrize"
  - "P0kemon"
  - "bcz"
  - "IIDK"
  - "yungsaphars"
  - "Swampie"
  - "ODxRay"
  - "Posed"
  - "Slexi"
  - "Zylowh"
  - "Elb1to"
  - "Zyphing"
  - "DANTEH"
  - "Topu"
  - "Futi"
  - "Glory"
  - "Reboting"
  - "Tylarzz"
  - "kayalust"
  - "Suchspeed"
  - "Tediosuy"
  - "Huahwi"
  - "NotDrizzy"
  - "Creaxx"
