# This configuration file is part of a Refine Development Project. Purchased at https://dsc.gg/refine

TABLIST:
  ENABLED: true
  UPDATE-INTERVAL: 20
SOCIAL:
  WEBSITE: www.refinedev.xyz
  TWITTER: '@RefineDev'
  STORE: www.refinedev.xyz
  DISCORD: dsc.gg/refine
LOCALE:
  HEADER:
    - ''
    - '&c&lRefine Network'
    - '&7&owww.refinedev.xyz'
    - ''
  FOOTER:
    - ''
    - '&c&oYou can buy our products and issue commissions at'
    - '&7discord.refinedev.xyz'
    - ''
SORT-RANKS:
  OWNER:
    PERMISSION: bolt.tablist.owner
    PRIORITY: 10
  MANAGER:
    PERMISSION: bolt.tablist.manager
    PRIORITY: 9
  DEVELOPER:
    PERMISSION: bolt.tablist.developer
    PRIORITY: 8
  MODERATOR:
    PERMISSION: bolt.tablist.moderator
    PRIORITY: 7
  HELPER:
    PERMISSION: bolt.tablist.helper
    PRIORITY: 6
  BUILDER:
    PERMISSION: bolt.tablist.builder
    PRIORITY: 5
  TRIAL:
    PERMISSION: bolt.tablist.trial
    PRIORITY: 4
  FAMOUS:
    PERMISSION: bolt.tablist.famous
    PRIORITY: 3
  MEDIA:
    PERMISSION: bolt.tablist.media
    PRIORITY: 2
  DONATOR:
    PERMISSION: bolt.tablist.donator
    PRIORITY: 1
  DEFAULT:
    PERMISSION: none
    PRIORITY: 0
LOBBY:
  LEFT:
    '1': ' '
    '2': '&7&m----------------'
    '3': '&c&lYour Profile'
    '4': '<dot_red>&fName: <profile_name>'
    '5': '<dot_red>&fPing: &e<profile_ping>'
    '6': ''
    '7': '&c&lStatistics'
    '8': '<dot_red>&fWins: &c<profile_wins>'
    '9': '<dot_red>&fKills: &c<profile_kills>'
    '10': '<dot_red>&fWL Ratio: &c<profile_wlr>'
    '11': '<dot_red>&fKD Ratio: &c<profile_kdr>'
    '12': '<dot_red>&fDivision: <profile_division>'
    '13': '<dot_red>&fGlobal ELO: &c<profile_global_elo>'
    '14': ''
    '15': ''
    '16': ''
    '17': ''
    '18': ''
    '19': '&b&lTwitter'
    '20': <skin_twitter><twitter>
  MIDDLE:
    '1': '&c&lPractice &7｜ &fEU'
    '2': '&7&m----------------'
    '3': '&c&lLobby Info'
    '4': '&f<dot_red>Online: &c<online_count>'
    '5': '&f<dot_red>Queueing: &c<in_queue>'
    '6': '&f<dot_red>Fighting: &c<in_fight>'
    '7': ''
    '8': ' '
    '9': ' '
    '10': ' '
    '11': ' '
    '12': ' '
    '13': ' '
    '14': ' '
    '15': ' '
    '16': ' '
    '17': ' '
    '18': ''
    '19': '&a&lWebsite'
    '20': <skin_website><website>
  RIGHT:
    '1': ' '
    '2': '&7&m----------------'
    '3': '&cYou are not in'
    '4': '&ca party!'
    '5': ''
    '6': '&7You can create a'
    '7': '&7party by using'
    '8': '&f/party create'
    '9': ' '
    '10': ' '
    '11': ' '
    '12': ' '
    '13': ' '
    '14': ' '
    '15': ' '
    '16': ' '
    '17': ' '
    '18': ''
    '19': '&9&lDiscord'
    '20': <skin_discord><discord>
  FAR-RIGHT:
    '1': ' '
    '2': ' '
    '3': ' '
    '4': ' '
    '5': ' '
    '6': ' '
    '7': '&c&lIMPORTANT NOTICE'
    '8': '&fPlease use'
    '9': '&fversion &c1.7'
    '10': '&ffor optimal'
    '11': '&fgameplay experience'
    '12': ' '
    '13': ' '
    '14': ' '
    '15': ' '
    '16': ' '
    '17': ' '
    '18': ' '
    '19': ' '
    '20': ' '
IN-PARTY:
  LEFT:
    '1': ' '
    '2': '&7&m----------------'
    '3': '&c&lYour Profile'
    '4': '<dot_red>&fName: &c<profile_name>'
    '5': '<dot_red>&fPing: &e<profile_ping>'
    '6': ''
    '7': '&c&lStatistics'
    '8': '<dot_red>&fWins: &c<profile_wins>'
    '9': '<dot_red>&fKills: &c<profile_kills>'
    '10': '<dot_red>&fWL Ratio: &c<profile_wlr>'
    '11': '<dot_red>&fKD Ratio: &c<profile_kdr>'
    '12': '<dot_red>&fDivision: <profile_division>'
    '13': '<dot_red>&fGlobal ELO: &c<profile_global_elo>'
    '14': ''
    '15': ''
    '16': ''
    '17': ''
    '18': ''
    '19': '&b&lTwitter'
    '20': <skin_twitter><twitter>
  MIDDLE:
    '1': '&c&lPractice &7｜ &fEU'
    '2': '&7&m----------------'
    '3': '&c&lLobby Info'
    '4': '&fOnline: &c<online_count>'
    '5': '&fIn Queue: &c<in_queue>'
    '6': '&fIn Fight: &c<in_fight>'
    '7': ''
    '8': ' '
    '9': ' '
    '10': ' '
    '11': ' '
    '12': ' '
    '13': ' '
    '14': ' '
    '15': ' '
    '16': ' '
    '17': ' '
    '18': ''
    '19': '&a&lWebsite'
    '20': <skin_website><website>
  RIGHT:
    '1': ' '
    '2': '&7&m----------------'
    '3': '&c&lParty Info'
    '4': '<dot_red>&fLeader: &c<party_leader>'
    '5': ''
    '6': '&cMembers'
    '7': <dot_red>&f<party_member_1>
    '8': <dot_red>&f<party_member_2>
    '9': <dot_red>&f<party_member_3>
    '10': <dot_red>&f<party_member_4>
    '11': <dot_red>&f<party_member_5>
    '12': <dot_red>&f<party_member_6>
    '13': <dot_red>&f<party_member_7>
    '14': <dot_red>&f<party_member_8>
    '15': <dot_red>&f<party_member_9>
    '16': <dot_red>&f<party_member_10>
    '17': ' '
    '18': ''
    '19': '&9&lDiscord'
    '20': <skin_discord><discord>
  FAR-RIGHT:
    '1': ' '
    '2': ' '
    '3': ' '
    '4': ' '
    '5': ' '
    '6': ' '
    '7': '&c&lIMPORTANT NOTICE'
    '8': '&fPlease use'
    '9': '&fversion &c1.7'
    '10': '&ffor optimal'
    '11': '&fgameplay experience'
    '12': ' '
    '13': ' '
    '14': ' '
    '15': ' '
    '16': ' '
    '17': ' '
    '18': ' '
    '19': ' '
    '20': ' '
MATCH:
  SOLO:
    LEFT:
      '1': ' '
      '2': '&7&m----------------'
      '3': ''
      '4': '&a&lYou'
      '5': '&a<your_player>'
      '6': ''
      '7': ' '
      '8': ' '
      '9': ' '
      '10': ' '
      '11': ' '
      '12': ' '
      '13': ' '
      '14': ' '
      '15': ' '
      '16': ' '
      '17': ' '
      '18': ''
      '19': '&b&lTwitter'
      '20': <skin_twitter><twitter>
    MIDDLE:
      '1': '&c&lPractice &7｜ &fEU'
      '2': '&7&m----------------'
      '3': '&c&lMatch Details'
      '4': '&fDuration: &c<match_duration>'
      '5': '&fArena: &c<match_arena>'
      '6': '&fKit: &c<match_kit>'
      '7': ''
      '8': ' '
      '9': ' '
      '10': ' '
      '11': ' '
      '12': ' '
      '13': ' '
      '14': ' '
      '15': ' '
      '16': ' '
      '17': ' '
      '18': ''
      '19': '&9&lDiscord'
      '20': <skin_discord><discord>
    RIGHT:
      '1': ' '
      '2': '&7&m----------------'
      '3': ''
      '4': '&c&lOpponent'
      '5': <opponent_player>
      '6': ''
      '7': ' '
      '8': ' '
      '9': ' '
      '10': ' '
      '11': ' '
      '12': ' '
      '13': ' '
      '14': ' '
      '15': ' '
      '16': ' '
      '17': ' '
      '18': ''
      '19': '&a&lWebsite'
      '20': <skin_website><website>
    FAR-RIGHT:
      '1': ' '
      '2': ' '
      '3': ' '
      '4': ' '
      '5': ' '
      '6': ' '
      '7': '&c&lIMPORTANT NOTICE'
      '8': '&fPlease use'
      '9': '&fversion &c1.8'
      '10': '&ffor optimal'
      '11': '&fgameplay experience'
      '12': ' '
      '13': ' '
      '14': ' '
      '15': ' '
      '16': ' '
      '17': ' '
      '18': ' '
      '19': ' '
      '20': ' '
  TEAM:
    LEFT:
      '1': ' '
      '2': '&7&m----------------'
      '3': ' '
      '4': '&a&lYour Team'
      '5': ''
      '6': '&a<team_1>'
      '7': '&a<team_2>'
      '8': '&a<team_3>'
      '9': '&a<team_4>'
      '10': '&a<team_5>'
      '11': '&a<team_6>'
      '12': '&a<team_7>'
      '13': '&a<team_8>'
      '14': '&a<team_9>'
      '15': '&a<team_10>'
      '16': '&a<team_11>'
      '17': '&a<team_12>'
      '18': ' '
      '19': '&b&lTwitter'
      '20': <skin_twitter><twitter>
    MIDDLE:
      '1': '&c&lPractice &7｜ &fEU'
      '2': '&7&m----------------'
      '3': '&c&lMatch Details'
      '4': '&fDuration: &c<match_duration>'
      '5': '&fArena: &c<match_arena>'
      '6': '&fKit: &c<match_kit>'
      '7': ''
      '8': ' '
      '9': ' '
      '10': ' '
      '11': ' '
      '12': ' '
      '13': ' '
      '14': ' '
      '15': ' '
      '16': ' '
      '17': ' '
      '18': ''
      '19': '&9&lDiscord'
      '20': <skin_discord><discord>
    RIGHT:
      '1': ' '
      '2': '&7&m----------------'
      '3': ' '
      '4': '&c&lOpponent Team'
      '5': ''
      '6': '&c<opponent_1>'
      '7': '&c<opponent_2>'
      '8': '&c<opponent_3>'
      '9': '&c<opponent_4>'
      '10': '&c<opponent_5>'
      '11': '&c<opponent_6>'
      '12': '&c<opponent_7>'
      '13': '&c<opponent_8>'
      '14': '&c<opponent_9>'
      '15': '&c<opponent_10>'
      '16': '&c<opponent_11>'
      '17': '&c<opponent_12>'
      '18': ' '
      '19': '&a&lWebsite'
      '20': <skin_website><website>
    FAR-RIGHT:
      '1': ' '
      '2': ' '
      '3': ' '
      '4': ' '
      '5': ' '
      '6': ' '
      '7': '&c&lIMPORTANT NOTICE'
      '8': '&fPlease use'
      '9': '&fversion &c1.7'
      '10': '&ffor optimal'
      '11': '&fgameplay experience'
      '12': ' '
      '13': ' '
      '14': ' '
      '15': ' '
      '16': ' '
      '17': ' '
      '18': ' '
      '19': ' '
      '20': ' '
  FFA:
    LEFT:
      '1': ' '
      '2': '&7&m----------------'
      '3': ''
      '4': ''
      '5': '&a<your_player>'
      '6': '&f<opponent_3>'
      '7': '&f<opponent_6>'
      '8': '&f<opponent_9>'
      '9': '&f<opponent_12>'
      '10': ''
      '11': ''
      '12': ''
      '13': ' '
      '14': ' '
      '15': ' '
      '16': ' '
      '17': ' '
      '18': ''
      '19': '&b&lTwitter'
      '20': <skin_twitter><twitter>
    MIDDLE:
      '1': '&c&lPractice &7｜ &fEU'
      '2': '&7&m----------------'
      '3': ''
      '4': ''
      '5': '&c&lParty FFA '
      '6': '&f<opponent_1> '
      '7': '&f<opponent_4> '
      '8': '&f<opponent_7> '
      '9': '&f<opponent_10> '
      '10': '&f<opponent_13> '
      '11': ''
      '12': ''
      '13': ' '
      '14': ' '
      '15': ' '
      '16': ' '
      '17': ' '
      '18': ''
      '19': '&9&lDiscord'
      '20': <skin_discord><discord>
    RIGHT:
      '1': ' '
      '2': '&7&m----------------'
      '3': ''
      '4': ''
      '5': '&f<opponent_2>'
      '6': '&f<opponent_5>'
      '7': '&f<opponent_8>'
      '8': '&f<opponent_11>'
      '9': '&f<opponent_14>'
      '10': ''
      '11': ''
      '12': ''
      '13': ''
      '14': ''
      '15': ''
      '16': ''
      '17': ''
      '18': ''
      '19': '&a&lWebsite'
      '20': <skin_website><website>
    FAR-RIGHT:
      '1': ' '
      '2': ' '
      '3': ' '
      '4': ' '
      '5': ' '
      '6': ' '
      '7': '&c&lIMPORTANT NOTICE'
      '8': '&fPlease use'
      '9': '&fversion &c1.7'
      '10': '&ffor optimal'
      '11': '&fgameplay experience'
      '12': ' '
      '13': ' '
      '14': ' '
      '15': ' '
      '16': ' '
      '17': ' '
      '18': ' '
      '19': ' '
      '20': ' '
SPECTATING:
  SOLO:
    LEFT:
      '1': ' '
      '2': '&7&m----------------'
      '3': ''
      '4': '&e&lPlayer 1'
      '5': '&e<player_a>'
      '6': ''
      '7': ' '
      '8': ' '
      '9': ' '
      '10': ' '
      '11': ' '
      '12': ' '
      '13': ' '
      '14': ' '
      '15': ' '
      '16': ' '
      '17': ' '
      '18': ''
      '19': '&b&lTwitter'
      '20': <skin_twitter><twitter>
    MIDDLE:
      '1': '&c&lPractice &7｜ &fEU'
      '2': '&7&m----------------'
      '3': '&c&lMatch Details'
      '4': '&fDuration: &c<match_duration>'
      '5': '&fArena: &c<match_arena>'
      '6': '&fKit: &c<match_kit>'
      '7': ''
      '8': ' '
      '9': ' '
      '10': ' '
      '11': ' '
      '12': ' '
      '13': ' '
      '14': ' '
      '15': ' '
      '16': ' '
      '17': ' '
      '18': ''
      '19': '&9&lDiscord'
      '20': <skin_discord><discord>
    RIGHT:
      '1': ' '
      '2': '&7&m----------------'
      '3': ''
      '4': '&e&lPlayer B'
      '5': '&e<player_b>'
      '6': ''
      '7': ' '
      '8': ' '
      '9': ' '
      '10': ' '
      '11': ' '
      '12': ' '
      '13': ' '
      '14': ' '
      '15': ' '
      '16': ' '
      '17': ' '
      '18': ''
      '19': '&a&lWebsite'
      '20': <skin_website><website>
    FAR-RIGHT:
      '1': ' '
      '2': ' '
      '3': ' '
      '4': ' '
      '5': ' '
      '6': ' '
      '7': '&c&lIMPORTANT NOTICE'
      '8': '&fPlease use'
      '9': '&fversion &c1.7'
      '10': '&ffor optimal'
      '11': '&fgameplay experience'
      '12': ' '
      '13': ' '
      '14': ' '
      '15': ' '
      '16': ' '
      '17': ' '
      '18': ' '
      '19': ' '
      '20': ' '
  TEAM:
    LEFT:
      '1': ' '
      '2': '&7&m----------------'
      '3': ' '
      '4': '&a&lTeam A'
      '5': ''
      '6': '&a<teamA_1>'
      '7': '&a<teamA_2>'
      '8': '&a<teamA_3>'
      '9': '&a<teamA_4>'
      '10': '&a<teamA_5>'
      '11': '&a<teamA_6>'
      '12': '&a<teamA_7>'
      '13': '&a<teamA_8>'
      '14': '&a<teamA_9>'
      '15': '&a<teamA_10>'
      '16': '&a<teamA_11>'
      '17': '&a<teamA_12>'
      '18': ' '
      '19': '&b&lTwitter'
      '20': <skin_twitter><twitter>
    MIDDLE:
      '1': '&c&lPractice &7｜ &fEU'
      '2': '&7&m----------------'
      '3': '&c&lMatch Details'
      '4': '&fDuration: &c<match_duration>'
      '5': '&fArena: &c<match_arena>'
      '6': '&fKit: &c<match_kit>'
      '7': ''
      '8': ' '
      '9': ' '
      '10': ' '
      '11': ' '
      '12': ' '
      '13': ' '
      '14': ' '
      '15': ' '
      '16': ' '
      '17': ' '
      '18': ''
      '19': '&9&lDiscord'
      '20': <skin_discord><discord>
    RIGHT:
      '1': ' '
      '2': '&7&m----------------'
      '3': ' '
      '4': '&c&lTeam B'
      '5': ''
      '6': '&c<teamB_1>'
      '7': '&c<teamB_2>'
      '8': '&c<teamB_3>'
      '9': '&c<teamB_4>'
      '10': '&c<teamB_5>'
      '11': '&c<teamB_6>'
      '12': '&c<teamB_7>'
      '13': '&c<teamB_8>'
      '14': '&c<teamB_9>'
      '15': '&c<teamB_10>'
      '16': '&c<teamB_11>'
      '17': '&c<teamB_12>'
      '18': ' '
      '19': '&a&lWebsite'
      '20': <skin_website><website>
    FAR-RIGHT:
      '1': ' '
      '2': ' '
      '3': ' '
      '4': ' '
      '5': ' '
      '6': ' '
      '7': '&c&lIMPORTANT NOTICE'
      '8': '&fPlease use'
      '9': '&fversion &c1.7'
      '10': '&ffor optimal'
      '11': '&fgameplay experience'
      '12': ' '
      '13': ' '
      '14': ' '
      '15': ' '
      '16': ' '
      '17': ' '
      '18': ' '
      '19': ' '
      '20': ' '
  FFA:
    LEFT:
      '1': ' '
      '2': '&7&m----------------'
      '3': ''
      '4': ''
      '5': ''
      '6': '&f<player_1>'
      '7': '&f<player_3>'
      '8': '&f<player_6'
      '9': '&f<player_9>'
      '10': '&f<player_12>'
      '11': ''
      '12': ''
      '13': ' '
      '14': ' '
      '15': ' '
      '16': ' '
      '17': ' '
      '18': ''
      '19': '&b&lTwitter'
      '20': <skin_twitter><twitter>
    MIDDLE:
      '1': '&c&lPractice &7｜ &fEU'
      '2': '&7&m----------------'
      '3': ''
      '4': ''
      '5': '&c&lParty FFA '
      '6': '&f<player_1> '
      '7': '&f<player_4> '
      '8': '&f<player_7> '
      '9': '&f<player_10> '
      '10': '&f<player_13> '
      '11': ''
      '12': ''
      '13': ' '
      '14': ' '
      '15': ' '
      '16': ' '
      '17': ' '
      '18': ''
      '19': '&9&lDiscord'
      '20': <skin_discord><discord>
    RIGHT:
      '1': ' '
      '2': '&7&m----------------'
      '3': ''
      '4': ''
      '5': ''
      '6': '&f<player_2>'
      '7': '&f<player_5>&'
      '8': f<player_8>
      '9': '&f<player_11>'
      '10': '&f<player_14>'
      '11': ''
      '12': ''
      '13': ''
      '14': ''
      '15': ''
      '16': ''
      '17': ''
      '18': ''
      '19': '&a&lWebsite'
      '20': <skin_website><website>
    FAR-RIGHT:
      '1': ' '
      '2': ' '
      '3': ' '
      '4': ' '
      '5': ' '
      '6': ' '
      '7': '&c&lIMPORTANT NOTICE'
      '8': '&fPlease use'
      '9': '&fversion &c1.7'
      '10': '&ffor optimal'
      '11': '&fgameplay experience'
      '12': ' '
      '13': ' '
      '14': ' '
      '15': ' '
      '16': ' '
      '17': ' '
      '18': ' '
      '19': ' '
      '20': ' '
